// ============================================================================
// robots.txt.ts
// ----------------------------------------------------------------------------
// Astro doesn't generate robots.txt automatically, so this is a small API
// route that returns one as plain text at build time. Points crawlers at
// the sitemap generated by src/pages/sitemap.xml.ts.
//
// This site is currently deployed to two hosts (Netlify = canonical,
// Cloudflare Pages = backup/staging copy). When this file is built AS PART
// OF the Cloudflare Pages build specifically (detected via
// SITE.isSecondaryDeployment, which checks Cloudflare's own CF_PAGES
// environment variable), it outputs a robots.txt that disallows all
// crawling — so that copy never competes with the canonical Netlify site
// in search results. The Netlify build outputs the normal, fully-open
// robots.txt.
// ============================================================================
import type { APIRoute } from "astro";
import { SITE } from "../lib/site";

export const GET: APIRoute = () => {
  const body = SITE.isSecondaryDeployment
    ? `User-agent: *\nDisallow: /\n`
    : `User-agent: *\nAllow: /\nSitemap: ${SITE.url}/sitemap.xml\n`;

  return new Response(body, {
    headers: { "Content-Type": "text/plain; charset=utf-8" },
  });
};
